### ISSUE TITLE
Kérdés

### ISSUE THREAD

**Issue by botiapa** [Xerren09/eKreta-WebAPI-documentation#1]
Hali, köszi a repot, amint te is megemlítetted, @bohapps nak van egy mobilos api doc-ja. Az lenne a kérdésem, hogy a két API miben tér el egymástol (ha nem egy és ugyanaz)?

**Comment by xsilent007** [comment]
A kréta 2 külön API-t használ a telefonos alkalmazáshoz és a webes felülethez. A telefonos API egy oauth2-szerű bearer tokent használ a bejelentkezéshez, amíg a webes API csak simán egy sütit. Valamint - saját obzerváció -, a webes api visszaadja normálisan, ha hétvégére olyan 'órákat' írnak be, mint "gyárlátogatás" / "osztálykirándulás" / stb. míg (legalábbis nekem) a mobilos api nem adja ezeket az 'órákat' vissza normálisan.

**Comment by botiapa** [comment]
Köszi a választ, zártam
